### ISSUE TITLE
add page transitions using react-router

### ISSUE THREAD

**Issue by stratospark** [stratospark/react-ss#3]
https://github.com/rackt/react-router/tree/master/examples/animations

Also, the code here might be helpful: https://github.com/andreypopp/react-router-page-transition/blob/master/index.js

Use css transitions from: http://tympanus.net/Development/PageTransitions/

**Comment by stratospark** [comment]
this might also be helpful: http://facebook.github.io/react/docs/animation.html

**Comment by stratospark** [comment]
Did some work in d7531d76f21d799a1f74e3265c863cb7b9e9ce91

We can try and figure out how to make the entire page width animation.

Also, another good exercise is to remove all the prefixes from animations.scss, and then to make the animation parametizable through sass functions

**Comment by igalgh** [comment]
I have change I want to review with you. It solves the animation width problem, but I'm not happy with the way it's done so I haven't submitted a fix. When you have time lets review it together?
