### ISSUE TITLE
static content serving broken (Linux) - routing issue?

### ISSUE THREAD

**Issue by igalgh** [stratospark/react-ss#6]
$ BROWSER_SYNC_RELOAD_DELAY_MS=800 gulp
browserSyncReloadDelayMs 800
[22:14:48] Using gulpfile /home/user/bckd/homedir/learn/node.js/react-ss/gulpfile.js
[22:14:48] Starting 'build'...
[22:14:48] Finished 'build' after 18 ms
[22:14:48] Starting 'browserify'...
[22:14:48] Finished 'browserify' after 15 ms
[22:14:48] Starting 'scss-watch'...
[22:14:48] Finished 'scss-watch' after 1.37 ms
[22:14:48] Starting 'nodemon'...
[gulp] [nodemon] v1.2.1
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: react/**/\* routes/**/\* app.js
[gulp] [nodemon] starting `node bin/www`
[22:14:49] Finished 'nodemon' after 395 ms
[22:14:49] Starting 'browser-sync'...
[22:14:49] Finished 'browser-sync' after 55 ms
[22:14:49] Starting 'default'...
[22:14:49] Finished 'default' after 20 μs
[BS] Proxying: http://localhost:3000
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:4000
[BS] External URL: http://192.168.1.132:4000
[BS] Watching files...
GET / 200 69.004 ms - 1343
Warning: No route matches path "/stylesheets/styles.css". Make sure you have <Route path="/stylesheets/styles.css"> somewhere in your <Routes>

**Comment by stratospark** [comment]
Can you "npm install" to make sure you have all the right packages.

On Wednesday, October 22, 2014, Igal Tivoni notifications@github.com
wrote:

> Assigned #6 https://github.com/stratospark/react-ss/issues/6 to
> @stratospark https://github.com/stratospark.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stratospark/react-ss/issues/6#event-181971467.

## 

-pr

**Comment by igalgh** [comment]
Looks like  I have everything installed. Last working commit (which does not contain this error) is 4907c90dd55dcb6d6f9ba8af196d82a4f0b5a940 and the commit which broke it is "\* Added react-router"

**Comment by stratospark** [comment]
this part is different. I wonder if you’re on HEAD of master?

[gulp] [nodemon] v1.2.1
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: react/**/\* routes/**/\* app.js
[gulp] [nodemon] starting `node bin/www`

**Comment by stratospark** [comment]
Thanks for fixing in 68a498447609700a6ab443e3a08cf3316806b858
